/*
 * Copyright 2016-2023 NXP SPDX-License-Identifier: BSD-3-Clause
 *
 * Automatically generated by svd-gen-header.py from MIMXRT595S_cm33.xml
 */
#pragma once

#include "hw/register.h"

/* Clock Controller 1 */
#define RT500_CLKCTL1_REGS_NO (526)

/* Clock Control 0 */
REG32(RT500_CLKCTL1_PSCCTL0, 0x10);
/* FlexIO clock control */
FIELD(RT500_CLKCTL1_PSCCTL0, FlexIO, 29, 1);

/* Clock Control 1 */
REG32(RT500_CLKCTL1_PSCCTL1, 0x14);

/* Clock Control 2 */
REG32(RT500_CLKCTL1_PSCCTL2, 0x18);

/* Clock Set 0 */
REG32(RT500_CLKCTL1_PSCCTL0_SET, 0x40);
/* FlexIO clock control */
FIELD(RT500_CLKCTL1_PSCCTL0_SET, FlexIO, 29, 1);

/* Clock Set 1 */
REG32(RT500_CLKCTL1_PSCCTL1_SET, 0x44);

/* Clock Set 2 */
REG32(RT500_CLKCTL1_PSCCTL2_SET, 0x48);

/* Clock Clear 0 */
REG32(RT500_CLKCTL1_PSCCTL0_CLR, 0x70);
/* FlexIO clock control clear */
FIELD(RT500_CLKCTL1_PSCCTL0_CLR, FlexIO, 29, 1);

/* Clock Clear 1 */
REG32(RT500_CLKCTL1_PSCCTL1_CLR, 0x74);

/* Clock Clear 2 */
REG32(RT500_CLKCTL1_PSCCTL2_CLR, 0x78);

/* Audio PLL0 PFD */
REG32(RT500_CLKCTL1_AUDIOPLL0PFD, 0x218);
/* PLL Fractional Divider 0 */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD0, 0, 6);
/* PFD0 Clock Ready Status Flag */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD0_CLKRDY, 6, 1);
/* PFD0 Clock Gate */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD0_CLKGATE, 7, 1);
/* PLL Fractional Divider 1 */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD1, 8, 6);
/* PFD1 Clock Ready Status Flag */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD1_CLKRDY, 14, 1);
/* PFD1 Clock Gate */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD1_CLKGATE, 15, 1);
/* PLL Fractional Divider 2 */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD2, 16, 6);
/* PFD2 Clock Ready Status Flag */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD2_CLKRDY, 22, 1);
/* PFD2 Clock Gate */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD2_CLKGATE, 23, 1);
/* PLL Fractional Divider 3 */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD3, 24, 6);
/* PFD3 Clock Ready Status Flag */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD3_CLKRDY, 30, 1);
/* PFD3 Clock Gate */
FIELD(RT500_CLKCTL1_AUDIOPLL0PFD, PFD3_CLKGATE, 31, 1);

/* OS Event Timer Functional Clock Select */
REG32(RT500_CLKCTL1_OSEVENTTFCLKSEL, 0x480);
/* OS Event Timer Functional Clock Source */
FIELD(RT500_CLKCTL1_OSEVENTTFCLKSEL, SEL, 0, 3);
/* Low Power Oscillator Clock (LPOSC) */
#define RT500_CLKCTL1_OSEVENTTFCLKSEL_SEL_LPOSC 0
/* RTC 32 KHz Clock */
#define RT500_CLKCTL1_OSEVENTTFCLKSEL_SEL_RTC_32KHZ 1
/* HCLK Free-Running Clock (Global Time Stamping) */
#define RT500_CLKCTL1_OSEVENTTFCLKSEL_SEL_TEAL 2
/* None, output gated to reduce power */
#define RT500_CLKCTL1_OSEVENTTFCLKSEL_SEL_NONE 7


#define RT500_CLKCTL1_REGISTER_ACCESS_INFO_ARRAY(_name) \
    struct RegisterAccessInfo _name[RT500_CLKCTL1_REGS_NO] = { \
        [0 ... RT500_CLKCTL1_REGS_NO - 1] = { \
            .name = "", \
            .addr = -1, \
        }, \
        [0x4] = { \
            .name = "PSCCTL0", \
            .addr = 0x10, \
            .ro = 0xD40000FF, \
            .reset = 0x0, \
        }, \
        [0x5] = { \
            .name = "PSCCTL1", \
            .addr = 0x14, \
            .ro = 0x4E7EFF00, \
            .reset = 0x0, \
        }, \
        [0x6] = { \
            .name = "PSCCTL2", \
            .addr = 0x18, \
            .ro = 0x3FFCFA60, \
            .reset = 0x0, \
        }, \
        [0x10] = { \
            .name = "PSCCTL0_SET", \
            .addr = 0x40, \
            .ro = 0xD40000FF, \
            .reset = 0x0, \
        }, \
        [0x11] = { \
            .name = "PSCCTL1_SET", \
            .addr = 0x44, \
            .ro = 0x4E7EFF00, \
            .reset = 0x0, \
        }, \
        [0x12] = { \
            .name = "PSCCTL2_SET", \
            .addr = 0x48, \
            .ro = 0x3FFCFA60, \
            .reset = 0x0, \
        }, \
        [0x1C] = { \
            .name = "PSCCTL0_CLR", \
            .addr = 0x70, \
            .ro = 0xD40000FF, \
            .reset = 0x0, \
        }, \
        [0x1D] = { \
            .name = "PSCCTL1_CLR", \
            .addr = 0x74, \
            .ro = 0x4E7EFF00, \
            .reset = 0x0, \
        }, \
        [0x1E] = { \
            .name = "PSCCTL2_CLR", \
            .addr = 0x78, \
            .ro = 0x3FFCFA60, \
            .reset = 0x0, \
        }, \
        [0x80] = { \
            .name = "AUDIOPLL0CLKSEL", \
            .addr = 0x200, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x81] = { \
            .name = "AUDIOPLL0CTL0", \
            .addr = 0x204, \
            .ro = 0xFF00DFFC, \
            .reset = 0x160002, \
        }, \
        [0x83] = { \
            .name = "AUDIOPLL0LOCKTIMEDIV2", \
            .addr = 0x20C, \
            .ro = 0xFFFF0000, \
            .reset = 0xCAFE, \
        }, \
        [0x84] = { \
            .name = "AUDIOPLL0NUM", \
            .addr = 0x210, \
            .ro = 0xC0000000, \
            .reset = 0x4DD2F15, \
        }, \
        [0x85] = { \
            .name = "AUDIOPLL0DENOM", \
            .addr = 0x214, \
            .ro = 0xC0000000, \
            .reset = 0x1FFFFFDB, \
        }, \
        [0x86] = { \
            .name = "AUDIOPLL0PFD", \
            .addr = 0x218, \
            .ro = 0x0, \
            .reset = 0x80808080, \
        }, \
        [0x90] = { \
            .name = "AUDIOPLLCLKDIV", \
            .addr = 0x240, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x100] = { \
            .name = "DSPCPUCLKDIV", \
            .addr = 0x400, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x10C] = { \
            .name = "DSPCPUCLKSELA", \
            .addr = 0x430, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x10D] = { \
            .name = "DSPCPUCLKSELB", \
            .addr = 0x434, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x120] = { \
            .name = "OSEVENTTFCLKSEL", \
            .addr = 0x480, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
        [0x140] = { \
            .name = "FRG0CLKSEL", \
            .addr = 0x500, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x141] = { \
            .name = "FRG0CTL", \
            .addr = 0x504, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x142] = { \
            .name = "FC0FCLKSEL", \
            .addr = 0x508, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x148] = { \
            .name = "FRG1CLKSEL", \
            .addr = 0x520, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x149] = { \
            .name = "FRG1CTL", \
            .addr = 0x524, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x14A] = { \
            .name = "FC1FCLKSEL", \
            .addr = 0x528, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x150] = { \
            .name = "FRG2CLKSEL", \
            .addr = 0x540, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x151] = { \
            .name = "FRG2CTL", \
            .addr = 0x544, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x152] = { \
            .name = "FC2FCLKSEL", \
            .addr = 0x548, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x158] = { \
            .name = "FRG3CLKSEL", \
            .addr = 0x560, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x159] = { \
            .name = "FRG3CTL", \
            .addr = 0x564, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x15A] = { \
            .name = "FC3FCLKSEL", \
            .addr = 0x568, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x160] = { \
            .name = "FRG4CLKSEL", \
            .addr = 0x580, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x161] = { \
            .name = "FRG4CTL", \
            .addr = 0x584, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x162] = { \
            .name = "FC4FCLKSEL", \
            .addr = 0x588, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x168] = { \
            .name = "FRG5CLKSEL", \
            .addr = 0x5A0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x169] = { \
            .name = "FRG5CTL", \
            .addr = 0x5A4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x16A] = { \
            .name = "FC5FCLKSEL", \
            .addr = 0x5A8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x170] = { \
            .name = "FRG6CLKSEL", \
            .addr = 0x5C0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x171] = { \
            .name = "FRG6CTL", \
            .addr = 0x5C4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x172] = { \
            .name = "FC6FCLKSEL", \
            .addr = 0x5C8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x178] = { \
            .name = "FRG7CLKSEL", \
            .addr = 0x5E0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x179] = { \
            .name = "FRG7CTL", \
            .addr = 0x5E4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x17A] = { \
            .name = "FC7FCLKSEL", \
            .addr = 0x5E8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x180] = { \
            .name = "FRG8CLKSEL", \
            .addr = 0x600, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x181] = { \
            .name = "FRG8CTL", \
            .addr = 0x604, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x182] = { \
            .name = "FC8FCLKSEL", \
            .addr = 0x608, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x188] = { \
            .name = "FRG9CLKSEL", \
            .addr = 0x620, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x189] = { \
            .name = "FRG9CTL", \
            .addr = 0x624, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x18A] = { \
            .name = "FC9FCLKSEL", \
            .addr = 0x628, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x190] = { \
            .name = "FRG10CLKSEL", \
            .addr = 0x640, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x191] = { \
            .name = "FRG10CTL", \
            .addr = 0x644, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x192] = { \
            .name = "FC10FCLKSEL", \
            .addr = 0x648, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x198] = { \
            .name = "FRG11CLKSEL", \
            .addr = 0x660, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x199] = { \
            .name = "FRG11CTL", \
            .addr = 0x664, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x19A] = { \
            .name = "FC11FCLKSEL", \
            .addr = 0x668, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A0] = { \
            .name = "FRG12CLKSEL", \
            .addr = 0x680, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A1] = { \
            .name = "FRG12CTL", \
            .addr = 0x684, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1A2] = { \
            .name = "FC12FCLKSEL", \
            .addr = 0x688, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A8] = { \
            .name = "FRG13CLKSEL", \
            .addr = 0x6A0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A9] = { \
            .name = "FRG13CTL", \
            .addr = 0x6A4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1AA] = { \
            .name = "FC13FCLKSEL", \
            .addr = 0x6A8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B0] = { \
            .name = "FRG14CLKSEL", \
            .addr = 0x6C0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B1] = { \
            .name = "FRG14CTL", \
            .addr = 0x6C4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1B2] = { \
            .name = "FC14FCLKSEL", \
            .addr = 0x6C8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B8] = { \
            .name = "FRG15CLKSEL", \
            .addr = 0x6E0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B9] = { \
            .name = "FRG15CTL", \
            .addr = 0x6E4, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1BA] = { \
            .name = "FC15FCLKSEL", \
            .addr = 0x6E8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1C0] = { \
            .name = "FRG16CLKSEL", \
            .addr = 0x700, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1C1] = { \
            .name = "FRG16CTL", \
            .addr = 0x704, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1C2] = { \
            .name = "FC16FCLKSEL", \
            .addr = 0x708, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1C8] = { \
            .name = "FRG17CLKSEL", \
            .addr = 0x720, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1C9] = { \
            .name = "FRG17CTL", \
            .addr = 0x724, \
            .ro = 0xFFFF0000, \
            .reset = 0xFF, \
        }, \
        [0x1CA] = { \
            .name = "FLEXIOCLKSEL", \
            .addr = 0x728, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1D0] = { \
            .name = "FLEXIOCLKDIV", \
            .addr = 0x740, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1D8] = { \
            .name = "FRGPLLCLKDIV", \
            .addr = 0x760, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1E0] = { \
            .name = "DMIC0FCLKSEL", \
            .addr = 0x780, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1E1] = { \
            .name = "DMIC0FCLKDIV", \
            .addr = 0x784, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1E8] = { \
            .name = "CT32BITFCLKSEL0", \
            .addr = 0x7A0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1E9] = { \
            .name = "CT32BITFCLKSEL1", \
            .addr = 0x7A4, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1EA] = { \
            .name = "CT32BITFCLKSEL2", \
            .addr = 0x7A8, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1EB] = { \
            .name = "CT32BITFCLKSEL3", \
            .addr = 0x7AC, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1EC] = { \
            .name = "CT32BITFCLKSEL4", \
            .addr = 0x7B0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1F0] = { \
            .name = "AUDIOMCLKSEL", \
            .addr = 0x7C0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1F1] = { \
            .name = "AUDIOMCLKDIV", \
            .addr = 0x7C4, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1F8] = { \
            .name = "CLKOUTSEL0", \
            .addr = 0x7E0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1F9] = { \
            .name = "CLKOUTSEL1", \
            .addr = 0x7E4, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1FA] = { \
            .name = "CLKOUTFCLKDIV", \
            .addr = 0x7E8, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x200] = { \
            .name = "I3C01FCLKSEL", \
            .addr = 0x800, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x201] = { \
            .name = "I3C01FCLKSTCSEL", \
            .addr = 0x804, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x202] = { \
            .name = "I3C01FCLKSTCDIV", \
            .addr = 0x808, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x203] = { \
            .name = "I3C01FCLKSDIV", \
            .addr = 0x80C, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x204] = { \
            .name = "I3C01FCLKDIV", \
            .addr = 0x810, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x205] = { \
            .name = "I3C01FCLKSTSTCLKSEL", \
            .addr = 0x814, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
        [0x208] = { \
            .name = "WDT1FCLKSEL", \
            .addr = 0x820, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
        [0x20C] = { \
            .name = "ACMP0FCLKSEL", \
            .addr = 0x830, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x20D] = { \
            .name = "ACMP0FCLKDIV", \
            .addr = 0x834, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
    }
