/*
 * Copyright 2016-2023 NXP SPDX-License-Identifier: BSD-3-Clause
 *
 * Automatically generated by svd-gen-header.py from MIMXRT595S_cm33.xml
 */
#pragma once

#include "hw/register.h"

/* Clock Controller 0 */
#define RT500_CLKCTL0_REGS_NO (490)

/* Clock Control 0 */
REG32(RT500_CLKCTL0_PSCCTL0, 0x10);
/* DSP clock control */
FIELD(RT500_CLKCTL0_PSCCTL0, DSP_CLK, 1, 1);
/* 128KB ROM Controller clock control */
FIELD(RT500_CLKCTL0_PSCCTL0, ROM_CTRLR_CLK, 2, 1);

/* Clock Control 1 */
REG32(RT500_CLKCTL0_PSCCTL1, 0x14);

/* Clock Control 2 */
REG32(RT500_CLKCTL0_PSCCTL2, 0x18);

/* Clock Control 0 Set */
REG32(RT500_CLKCTL0_PSCCTL0_SET, 0x40);
/* DSP clock set */
FIELD(RT500_CLKCTL0_PSCCTL0_SET, DSP_CLK, 1, 1);
/* 128KB ROM Controller clock set */
FIELD(RT500_CLKCTL0_PSCCTL0_SET, ROM_CTRLR_CLK, 2, 1);

/* Clock Control 1 Set */
REG32(RT500_CLKCTL0_PSCCTL1_SET, 0x44);

/* Clock Control 2 Set */
REG32(RT500_CLKCTL0_PSCCTL2_SET, 0x48);

/* Clock Control 0 Clear */
REG32(RT500_CLKCTL0_PSCCTL0_CLR, 0x70);
/* DSP clock clear */
FIELD(RT500_CLKCTL0_PSCCTL0_CLR, DSP_CLK, 1, 1);
/* 128KB ROM Controller clock clear */
FIELD(RT500_CLKCTL0_PSCCTL0_CLR, ROM_CTRLR_CLK, 2, 1);

/* Clock Control 1 Clear */
REG32(RT500_CLKCTL0_PSCCTL1_CLR, 0x74);

/* Clock Control 2 Clear */
REG32(RT500_CLKCTL0_PSCCTL2_CLR, 0x78);

/* FRO Clock Status */
REG32(RT500_CLKCTL0_FROCLKSTATUS, 0x10C);

/* System PLL0 PFD */
REG32(RT500_CLKCTL0_SYSPLL0PFD, 0x218);
/* PLL Fractional Divider 0 */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD0, 0, 6);
/* PFD0 Clock Ready Status Flag */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD0_CLKRDY, 6, 1);
/* PFD0 Clock Gate */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD0_CLKGATE, 7, 1);
/* PLL Fractional Divider 1 */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD1, 8, 6);
/* PFD1 Clock Ready Status Flag */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD1_CLKRDY, 14, 1);
/* PFD1 Clock Gate */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD1_CLKGATE, 15, 1);
/* PLL Fractional Divider 2 */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD2, 16, 6);
/* PFD2 Clock Ready Status Flag */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD2_CLKRDY, 22, 1);
/* PFD2 Clock Gate */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD2_CLKGATE, 23, 1);
/* PLL Fractional Divider 3 */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD3, 24, 6);
/* PFD3 Clock Ready Status Flag */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD3_CLKRDY, 30, 1);
/* PFD3 Clock Gate */
FIELD(RT500_CLKCTL0_SYSPLL0PFD, PFD3_CLKGATE, 31, 1);

/* SYSTICK Functional Clock Select */
REG32(RT500_CLKCTL0_SYSTICKFCLKSEL, 0x760);
/* Select Clock Source */
FIELD(RT500_CLKCTL0_SYSTICKFCLKSEL, SEL, 0, 3);
/* Systick Divider Output Clock */
#define RT500_CLKCTL0_SYSTICKFCLKSEL_SEL_SYSTICK_DIV_OUTPUT 0
/* Low Power Oscillator Clock (LPOSC) */
#define RT500_CLKCTL0_SYSTICKFCLKSEL_SEL_LPOSC 1
/* 32 KHz RTC Clock */
#define RT500_CLKCTL0_SYSTICKFCLKSEL_SEL_A32KHZ_RTC 2
/* None; this may be selected to reduce power when no output is needed. */
#define RT500_CLKCTL0_SYSTICKFCLKSEL_SEL_NONE 7

/* SYSTICK Functional Clock Divider */
REG32(RT500_CLKCTL0_SYSTICKFCLKDIV, 0x764);
/* Clock Divider Value Selection */
FIELD(RT500_CLKCTL0_SYSTICKFCLKDIV, DIV, 0, 8);
/* Reset the Divider Counter */
FIELD(RT500_CLKCTL0_SYSTICKFCLKDIV, RESET, 29, 1);
/* Halt the Divider Counter */
FIELD(RT500_CLKCTL0_SYSTICKFCLKDIV, HALT, 30, 1);
/* Divider status flag */
FIELD(RT500_CLKCTL0_SYSTICKFCLKDIV, REQFLAG, 31, 1);


#define RT500_CLKCTL0_REGISTER_ACCESS_INFO_ARRAY(_name) \
    struct RegisterAccessInfo _name[RT500_CLKCTL0_REGS_NO] = { \
        [0 ... RT500_CLKCTL0_REGS_NO - 1] = { \
            .name = "", \
            .addr = -1, \
        }, \
        [0x4] = { \
            .name = "PSCCTL0", \
            .addr = 0x10, \
            .ro = 0xA208E0E1, \
            .reset = 0x5, \
        }, \
        [0x5] = { \
            .name = "PSCCTL1", \
            .addr = 0x14, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x0, \
        }, \
        [0x6] = { \
            .name = "PSCCTL2", \
            .addr = 0x18, \
            .ro = 0xDFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x10] = { \
            .name = "PSCCTL0_SET", \
            .addr = 0x40, \
            .ro = 0xA208E0E1, \
            .reset = 0x0, \
        }, \
        [0x11] = { \
            .name = "PSCCTL1_SET", \
            .addr = 0x44, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x0, \
        }, \
        [0x12] = { \
            .name = "PSCCTL2_SET", \
            .addr = 0x48, \
            .ro = 0xDFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x1C] = { \
            .name = "PSCCTL0_CLR", \
            .addr = 0x70, \
            .ro = 0xA208E0E1, \
            .reset = 0x0, \
        }, \
        [0x1D] = { \
            .name = "PSCCTL1_CLR", \
            .addr = 0x74, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x0, \
        }, \
        [0x1E] = { \
            .name = "PSCCTL2_CLR", \
            .addr = 0x78, \
            .ro = 0xDFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x20] = { \
            .name = "FRO_CONTROL", \
            .addr = 0x80, \
            .ro = 0x7C000000, \
            .reset = 0x0, \
        }, \
        [0x21] = { \
            .name = "FRO_CAPVAL", \
            .addr = 0x84, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x23] = { \
            .name = "FRO_RDTRIM", \
            .addr = 0x8C, \
            .ro = 0xFFFFF800, \
            .reset = 0x3BF, \
        }, \
        [0x24] = { \
            .name = "FRO_SCTRIM", \
            .addr = 0x90, \
            .ro = 0xFFFFFFC0, \
            .reset = 0x20, \
        }, \
        [0x42] = { \
            .name = "FRODIVSEL", \
            .addr = 0x108, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x43] = { \
            .name = "FROCLKSTATUS", \
            .addr = 0x10C, \
            .ro = 0xFFFFFFFF, \
            .reset = 0x0, \
        }, \
        [0x44] = { \
            .name = "FRODIVOEN", \
            .addr = 0x110, \
            .ro = 0xFFFFFFE0, \
            .reset = 0x0, \
        }, \
        [0x4C] = { \
            .name = "LOWFREQCLKDIV", \
            .addr = 0x130, \
            .ro = 0x1FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x58] = { \
            .name = "SYSOSCCTL0", \
            .addr = 0x160, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x5A] = { \
            .name = "SYSOSCBYPASS", \
            .addr = 0x168, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
        [0x64] = { \
            .name = "LPOSCCTL0", \
            .addr = 0x190, \
            .ro = 0x7FFFFFFF, \
            .reset = 0x807BC4D4, \
        }, \
        [0x70] = { \
            .name = "OSC32KHZCTL0", \
            .addr = 0x1C0, \
            .ro = 0xFFFFFFFE, \
            .reset = 0x0, \
        }, \
        [0x80] = { \
            .name = "SYSPLL0CLKSEL", \
            .addr = 0x200, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x81] = { \
            .name = "SYSPLL0CTL0", \
            .addr = 0x204, \
            .ro = 0xFF00DFFC, \
            .reset = 0x160002, \
        }, \
        [0x83] = { \
            .name = "SYSPLL0LOCKTIMEDIV2", \
            .addr = 0x20C, \
            .ro = 0xFFFF0000, \
            .reset = 0xCAFE, \
        }, \
        [0x84] = { \
            .name = "SYSPLL0NUM", \
            .addr = 0x210, \
            .ro = 0xC0000000, \
            .reset = 0x4DD2F15, \
        }, \
        [0x85] = { \
            .name = "SYSPLL0DENOM", \
            .addr = 0x214, \
            .ro = 0xC0000000, \
            .reset = 0x1FFFFFDB, \
        }, \
        [0x86] = { \
            .name = "SYSPLL0PFD", \
            .addr = 0x218, \
            .ro = 0x0, \
            .reset = 0x80808080, \
        }, \
        [0x90] = { \
            .name = "MAINPLLCLKDIV", \
            .addr = 0x240, \
            .ro = 0x1FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x91] = { \
            .name = "DSPPLLCLKDIV", \
            .addr = 0x244, \
            .ro = 0x1FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x92] = { \
            .name = "AUX0PLLCLKDIV", \
            .addr = 0x248, \
            .ro = 0x1FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x93] = { \
            .name = "AUX1PLLCLKDIV", \
            .addr = 0x24C, \
            .ro = 0x1FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x100] = { \
            .name = "SYSCPUAHBCLKDIV", \
            .addr = 0x400, \
            .ro = 0x7FFFFF00, \
            .reset = 0x0, \
        }, \
        [0x10C] = { \
            .name = "MAINCLKSELA", \
            .addr = 0x430, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x10D] = { \
            .name = "MAINCLKSELB", \
            .addr = 0x434, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x140] = { \
            .name = "PFC0DIV", \
            .addr = 0x500, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x141] = { \
            .name = "PFC1DIV", \
            .addr = 0x504, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x188] = { \
            .name = "FLEXSPI0FCLKSEL", \
            .addr = 0x620, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x189] = { \
            .name = "FLEXSPI0FCLKDIV", \
            .addr = 0x624, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x18C] = { \
            .name = "FLEXSPI1FCLKSEL", \
            .addr = 0x630, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x18D] = { \
            .name = "FLEXSPI1FCLKDIV", \
            .addr = 0x634, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x190] = { \
            .name = "SCTFCLKSEL", \
            .addr = 0x640, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x191] = { \
            .name = "SCTIN7CLKDIV", \
            .addr = 0x644, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x198] = { \
            .name = "USBHSFCLKSEL", \
            .addr = 0x660, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x199] = { \
            .name = "USBHSFCLKDIV", \
            .addr = 0x664, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1A0] = { \
            .name = "SDIO0FCLKSEL", \
            .addr = 0x680, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A1] = { \
            .name = "SDIO0FCLKDIV", \
            .addr = 0x684, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1A4] = { \
            .name = "SDIO1FCLKSEL", \
            .addr = 0x690, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1A5] = { \
            .name = "SDIO1FCLKDIV", \
            .addr = 0x694, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1B4] = { \
            .name = "ADC0FCLKSEL0", \
            .addr = 0x6D0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B5] = { \
            .name = "ADC0FCLKSEL1", \
            .addr = 0x6D4, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1B6] = { \
            .name = "ADC0FCLKDIV", \
            .addr = 0x6D8, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1C0] = { \
            .name = "UTICKFCLKSEL", \
            .addr = 0x700, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1C8] = { \
            .name = "WDT0FCLKSEL", \
            .addr = 0x720, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x0, \
        }, \
        [0x1CC] = { \
            .name = "A32KHZWAKECLKSEL", \
            .addr = 0x730, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x1, \
        }, \
        [0x1CD] = { \
            .name = "A32KHZWAKECLKDIV", \
            .addr = 0x734, \
            .ro = 0x1FFFFF00, \
            .reset = 0x1F, \
        }, \
        [0x1D8] = { \
            .name = "SYSTICKFCLKSEL", \
            .addr = 0x760, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1D9] = { \
            .name = "SYSTICKFCLKDIV", \
            .addr = 0x764, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1DC] = { \
            .name = "DPHYCLKSEL", \
            .addr = 0x770, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1DD] = { \
            .name = "DPHYCLKDIV", \
            .addr = 0x774, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1DE] = { \
            .name = "DPHYESCCLKSEL", \
            .addr = 0x778, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1DF] = { \
            .name = "DPHYESCRXCLKDIV", \
            .addr = 0x77C, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000010, \
        }, \
        [0x1E0] = { \
            .name = "DPHYESCTXCLKDIV", \
            .addr = 0x780, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000011, \
        }, \
        [0x1E4] = { \
            .name = "GPUCLKSEL", \
            .addr = 0x790, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1E5] = { \
            .name = "GPUCLKDIV", \
            .addr = 0x794, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
        [0x1E8] = { \
            .name = "DCPIXELCLKSEL", \
            .addr = 0x7A0, \
            .ro = 0xFFFFFFF8, \
            .reset = 0x7, \
        }, \
        [0x1E9] = { \
            .name = "DCPIXELCLKDIV", \
            .addr = 0x7A4, \
            .ro = 0x1FFFFF00, \
            .reset = 0x40000000, \
        }, \
    }
