/*
 * Copyright 2016-2023 NXP SPDX-License-Identifier: BSD-3-Clause
 *
 * Automatically generated by svd-gen-header.py from MIMXRT595S_cm33.xml
 */
#pragma once

#include "hw/register.h"

/* Reset Controller 0 */
#define RT500_RSTCTL0_REGS_NO (31)

/* System Reset Status Register */
REG32(RT500_RSTCTL0_SYSRSTSTAT, 0x0);

/* Peripheral Reset Control Register 0 */
REG32(RT500_RSTCTL0_PRSTCTL0, 0x10);

/* Peripheral Reset Control Register 1 */
REG32(RT500_RSTCTL0_PRSTCTL1, 0x14);

/* Peripheral Reset Control Register 2 */
REG32(RT500_RSTCTL0_PRSTCTL2, 0x18);

/* Peripheral Reset Control Register 0 SET */
REG32(RT500_RSTCTL0_PRSTCTL0_SET, 0x40);

/* Peripheral Reset Control Register 1 SET */
REG32(RT500_RSTCTL0_PRSTCTL1_SET, 0x44);

/* Peripheral Reset Control Register 2 SET */
REG32(RT500_RSTCTL0_PRSTCTL2_SET, 0x48);

/* Peripheral Reset Control Register 0 CLR */
REG32(RT500_RSTCTL0_PRSTCTL0_CLR, 0x70);

/* Peripheral Reset Control Register 1 CLR */
REG32(RT500_RSTCTL0_PRSTCTL1_CLR, 0x74);

/* Peripheral Reset Control Register 2 CLR */
REG32(RT500_RSTCTL0_PRSTCTL2_CLR, 0x78);


#define RT500_RSTCTL0_REGISTER_ACCESS_INFO_ARRAY(_name) \
    struct RegisterAccessInfo _name[RT500_RSTCTL0_REGS_NO] = { \
        [0 ... RT500_RSTCTL0_REGS_NO - 1] = { \
            .name = "", \
            .addr = -1, \
        }, \
        [0x0] = { \
            .name = "SYSRSTSTAT", \
            .addr = 0x0, \
            .ro = 0xFFFFFF0E, \
            .reset = 0x1, \
        }, \
        [0x4] = { \
            .name = "PRSTCTL0", \
            .addr = 0x10, \
            .ro = 0x820AE0F5, \
            .reset = 0x7DF51F0A, \
        }, \
        [0x5] = { \
            .name = "PRSTCTL1", \
            .addr = 0x14, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x101800C, \
        }, \
        [0x6] = { \
            .name = "PRSTCTL2", \
            .addr = 0x18, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x1C000001, \
        }, \
        [0x10] = { \
            .name = "PRSTCTL0_SET", \
            .addr = 0x40, \
            .ro = 0x820AE0F5, \
            .reset = 0x0, \
        }, \
        [0x11] = { \
            .name = "PRSTCTL1_SET", \
            .addr = 0x44, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x0, \
        }, \
        [0x12] = { \
            .name = "PRSTCTL2_SET", \
            .addr = 0x48, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
        [0x1C] = { \
            .name = "PRSTCTL0_CLR", \
            .addr = 0x70, \
            .ro = 0x820AE0F5, \
            .reset = 0x0, \
        }, \
        [0x1D] = { \
            .name = "PRSTCTL1_CLR", \
            .addr = 0x74, \
            .ro = 0xFEFE7FF3, \
            .reset = 0x0, \
        }, \
        [0x1E] = { \
            .name = "PRSTCTL2_CLR", \
            .addr = 0x78, \
            .ro = 0xFFFFFFFC, \
            .reset = 0x0, \
        }, \
    }
