[workspace]
resolver = "2"
members = [
    "qemu-api-macros",
    "qemu-api",
    "hw/char/pl011",
]

[workspace.lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = [
    'cfg(MESON)', 'cfg(HAVE_GLIB_WITH_ALIGNED_ALLOC)',
    'cfg(has_offset_of)'] }

# Prohibit code that is forbidden in Rust 2024
unsafe_op_in_unsafe_fn = "deny"
